name: myunivokai-local

include:
  - ./infra/docker-compose-local.yml
  - ./services/api-gateway/docker-compose-local.yml
  - ./services/dna-service/docker-compose-local.yml
  - ./services/universe-service/docker-compose-local.yml
  - ./services/nature-service/docker-compose-local.yml
  - ./apps/myunivokai-web/docker-compose-local.yml
