// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check (liveness)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check (dependencies)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/share/worlds/{shareSlug}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "share"
                ],
                "summary": "Get public universe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share slug",
                        "name": "shareSlug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicWorldResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/worlds": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Get universes by ids",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated world IDs (max 50)",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Create universe",
                "parameters": [
                    {
                        "description": "World input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.CreateWorldResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/worlds/{worldId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Get universe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "World ID",
                        "name": "worldId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/worlds/{worldId}/publish": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Publish universe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "World ID",
                        "name": "worldId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublishResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/worlds/{worldId}/variants": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Regenerate universe variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "World ID",
                        "name": "worldId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.VariantResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/worlds/{worldId}/variants/{variantId}/select": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "worlds"
                ],
                "summary": "Select universe variant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "World ID",
                        "name": "worldId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Variant ID",
                        "name": "variantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.VariantResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_httpx.ErrorBody"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.BeltConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "gapBeyondLastOrbit": {
                    "type": "number"
                },
                "instanceCount": {
                    "type": "integer"
                },
                "rockColor": {
                    "type": "string"
                },
                "tiltXRadians": {
                    "type": "number"
                },
                "tiltZRadians": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.CameraConfig": {
            "type": "object",
            "properties": {
                "distance": {
                    "type": "number"
                },
                "fov": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.CometsConfig": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "tailLengthMultiplier": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.ConstellationConfig": {
            "type": "object",
            "properties": {
                "displayCount": {
                    "type": "integer"
                },
                "glowMultiplier": {
                    "type": "number"
                },
                "lineColor": {
                    "type": "string"
                },
                "rotationRadiansPerSecond": {
                    "type": "number"
                },
                "seed": {
                    "type": "string"
                },
                "starColor": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.CoreConfig": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "emissive": {
                    "type": "string"
                },
                "scale": {
                    "type": "number"
                },
                "shape": {
                    "type": "string"
                },
                "spinSpeed": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.CreateWorldResponse": {
            "type": "object",
            "properties": {
                "personalityDNA": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PersonalityDNA"
                },
                "variant": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldVariant"
                },
                "world": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.World"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.DNAPlanet": {
            "type": "object",
            "properties": {
                "energy": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "meaning": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.EnergySignature": {
            "type": "object",
            "properties": {
                "intensity": {
                    "type": "integer"
                },
                "primary": {
                    "type": "string"
                },
                "secondary": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.HUDConfig": {
            "type": "object",
            "properties": {
                "showLabels": {
                    "type": "boolean"
                },
                "showTraitBars": {
                    "type": "boolean"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.MilkyWayConfig": {
            "type": "object",
            "properties": {
                "allSkyStarCount": {
                    "type": "integer"
                },
                "bandStarCount": {
                    "type": "integer"
                },
                "bandTiltXRadians": {
                    "type": "number"
                },
                "bandTiltZRadians": {
                    "type": "number"
                },
                "coreCloudColors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor"
                    }
                },
                "coreCloudCount": {
                    "type": "integer"
                },
                "coreCloudOpacity": {
                    "type": "number"
                },
                "coreStarColors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor"
                    }
                },
                "coreStarCount": {
                    "type": "integer"
                },
                "dustCloudColors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor"
                    }
                },
                "dustCloudCount": {
                    "type": "integer"
                },
                "dustCloudOpacity": {
                    "type": "number"
                },
                "heroStarCount": {
                    "type": "integer"
                },
                "nebulaCloudColors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor"
                    }
                },
                "nebulaCloudCount": {
                    "type": "integer"
                },
                "nebulaCloudOpacity": {
                    "type": "number"
                },
                "rotationRadiansPerSecond": {
                    "type": "number"
                },
                "seed": {
                    "type": "string"
                },
                "starColors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor"
                    }
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.Palette": {
            "type": "object",
            "properties": {
                "accent": {
                    "type": "string"
                },
                "background": {
                    "type": "string"
                },
                "gradient": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "primary": {
                    "type": "string"
                },
                "secondary": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.ParticleConfig": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "desktopCount": {
                    "type": "integer"
                },
                "mobileCount": {
                    "type": "integer"
                },
                "spread": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PersonalityDNA": {
            "type": "object",
            "properties": {
                "archetype": {
                    "type": "string"
                },
                "energySignature": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.EnergySignature"
                },
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.DNAPlanet"
                    }
                },
                "quote": {
                    "type": "string"
                },
                "sceneName": {
                    "type": "string"
                },
                "schemaVersion": {
                    "type": "string"
                },
                "shortNarrative": {
                    "type": "string"
                },
                "traitScores": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.TraitScores"
                },
                "visualHints": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.VisualHints"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PlanetSceneConfig": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "energy": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "meaning": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orbitRadius": {
                    "type": "number"
                },
                "orbitSpeed": {
                    "type": "number"
                },
                "phase": {
                    "type": "number"
                },
                "size": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PostFXConfig": {
            "type": "object",
            "properties": {
                "bloomIntensity": {
                    "type": "number"
                },
                "grade": {
                    "description": "Grade was added in schemaVersion 1.2. Pointer + omitempty; the frontend\nfalls back to its per-theme grade table when the key is absent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PostFXGradeConfig"
                        }
                    ]
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PostFXGradeConfig": {
            "type": "object",
            "properties": {
                "brightness": {
                    "type": "number"
                },
                "contrast": {
                    "type": "number"
                },
                "hueRadians": {
                    "type": "number"
                },
                "saturation": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicDNA": {
            "type": "object",
            "properties": {
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.DNAPlanet"
                    }
                },
                "traitScores": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.TraitScores"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicVariant": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldSceneConfig"
                },
                "seed": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicWorld": {
            "type": "object",
            "properties": {
                "archetype": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "sceneName": {
                    "type": "string"
                },
                "shortNarrative": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicWorldResponse": {
            "type": "object",
            "properties": {
                "publicDNA": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicDNA"
                },
                "variant": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicVariant"
                },
                "world": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublicWorld"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.PublishResponse": {
            "type": "object",
            "properties": {
                "shareSlug": {
                    "type": "string"
                },
                "shareUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.SkyConfig": {
            "type": "object",
            "properties": {
                "constellations": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.ConstellationConfig"
                },
                "milkyWay": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.MilkyWayConfig"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.SunConfig": {
            "type": "object",
            "properties": {
                "glowColor": {
                    "type": "string"
                },
                "lightColor": {
                    "type": "string"
                },
                "surfaceHdrMultiplier": {
                    "type": "number"
                },
                "surfaceTintColor": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.TraitScores": {
            "type": "object",
            "properties": {
                "creativity": {
                    "type": "integer"
                },
                "curiosity": {
                    "type": "integer"
                },
                "discipline": {
                    "type": "integer"
                },
                "energy": {
                    "type": "integer"
                },
                "focus": {
                    "type": "integer"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.VariantResponse": {
            "type": "object",
            "properties": {
                "variant": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldVariant"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.VisualHints": {
            "type": "object",
            "properties": {
                "coreSymbol": {
                    "type": "string"
                },
                "motionIntent": {
                    "type": "string"
                },
                "paletteIntent": {
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WeightedColor": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.World": {
            "type": "object",
            "properties": {
                "archetype": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sceneName": {
                    "type": "string"
                },
                "selectedVariantId": {
                    "type": "string"
                },
                "shareSlug": {
                    "type": "string"
                },
                "shortNarrative": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldInput": {
            "type": "object",
            "properties": {
                "challenge": {
                    "type": "string"
                },
                "favoriteColors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "goal": {
                    "type": "string"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mood": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "preferredWorldStyle": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "traits": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldListResponse": {
            "type": "object",
            "properties": {
                "worlds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldResponse"
                    }
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldResponse": {
            "type": "object",
            "properties": {
                "personalityDNA": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PersonalityDNA"
                },
                "selectedVariant": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldVariant"
                },
                "variants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldVariant"
                    }
                },
                "world": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.World"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldSceneConfig": {
            "type": "object",
            "properties": {
                "archetype": {
                    "type": "string"
                },
                "belt": {
                    "description": "Belt, Comets and Sun were added in schemaVersion 1.2 (the scene diversity\nround). Pointer + omitempty like Sky: configs stored before 1.2 have no\nkeys and the frontend renders its built-in defaults, so old worlds keep\nlooking exactly as they did.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.BeltConfig"
                        }
                    ]
                },
                "camera": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.CameraConfig"
                },
                "comets": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.CometsConfig"
                },
                "core": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.CoreConfig"
                },
                "hud": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.HUDConfig"
                },
                "palette": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.Palette"
                },
                "particles": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.ParticleConfig"
                },
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PlanetSceneConfig"
                    }
                },
                "postFX": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.PostFXConfig"
                },
                "quote": {
                    "type": "string"
                },
                "sceneName": {
                    "type": "string"
                },
                "schemaVersion": {
                    "type": "string"
                },
                "sky": {
                    "description": "Sky was added in schemaVersion 1.1. Pointer + omitempty so configs stored\nbefore that keep round-tripping without a sky key; the frontend falls back\nto its built-in sky defaults when the key is absent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.SkyConfig"
                        }
                    ]
                },
                "sun": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.SunConfig"
                },
                "theme": {
                    "type": "string"
                }
            }
        },
        "github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldVariant": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/github_com_myunivokai_myunivokai_services_universe-service_internal_models.WorldSceneConfig"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isSelected": {
                    "type": "boolean"
                },
                "seed": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "variantNo": {
                    "type": "integer"
                },
                "worldId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Myunivokai API",
	Description:      "Backend API for Myunivokai personal universe generation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
