FROM golang:1.25-alpine

WORKDIR /workspace/services/api-gateway
COPY contracts/go /workspace/contracts/go
COPY services/api-gateway/go.mod services/api-gateway/go.sum ./
RUN go mod download

CMD ["go", "run", "./cmd/gateway"]
