FROM golang:1.25-alpine

WORKDIR /workspace/services/universe-service
COPY contracts/go /workspace/contracts/go
COPY services/universe-service/go.mod services/universe-service/go.sum ./
RUN go mod download

CMD ["go", "run", "./cmd/service"]
